### ISSUE TITLE
Is the connection standard?

### ISSUE THREAD

**Issue by alexiscatnip** [maifeeulasad/Android-IP-Camera#1]
In the app, I input the IP of my PC (not mobile phone) + 8888 as the port

and on my PC, I open VLC and point it to the IP of the mobile phone, like this:
![image](https://user-images.githubusercontent.com/42345054/165127780-9aa0643a-200c-4cad-bf9d-afdf22d4522d.png)

It doesn't work, so it seems that the network connection in this repo is a non-standard protocol?

**Comment by walidelrifai** [comment]
facing the same issue.. did you manage to find a fix?

**Comment by alexiscatnip** [comment]
@walidelrifai I think its just sending the image as bytes without encoding into some video stream like MJPG. So no wonder that VLC won't decode it.

**Comment by wwzh2015** [comment]
> bytes without encoding

Me too, How to run it?
